Solve #139 Retirar upvote e voto de confirmação
Eccoar/2020.2-Eccoar_Gateway pull request #16
Opened 2021-04-17 02:22 UTC by luiz-herique

## Conteúdo

Neste pull request se realizou:

- Gerenciamento da função de remover voto e upvote
- Testes da nova funcionalidade

## Checklist

- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-04-17 15:56 UTC, MatheusBlanco requested changes
Boa gente, mas queria falar daqui a mesma preocupação que deixei no PR de complaint, sobre ter função de outra branch que ainda não foi merjada aqui

2021-04-17 15:56 UTC, MatheusBlanco commented on src/routes.ts
> +routers.delete('/api/vote/remove', async (req: Request, resp: Response) => {
Mudem essa rota para /api/votes e apenas chamem o método de delete. Que nem comentei no PR de deletar denúncia

2021-04-18 01:32 UTC, luiz-herique commented on src/routes.ts
> +routers.delete('/api/vote/remove', async (req: Request, resp: Response) => {
Obrigado pela revisão, rota alterada.

2021-04-18 01:33 UTC, luiz-herique commented on src/routes.ts
> +routers.delete('/api/vote/remove', async (req: Request, resp: Response) => {
O que falta: 

- Mudar maneira em que está sendo utilizado o metodo

2021-04-18 13:47 UTC, MatheusBlanco commented on src/routes.ts
> +routers.delete('/api/vote/remove', async (req: Request, resp: Response) => {
Show. Eu deixei um comentário novo lá no PR do gateway da issue 153. Acho que vai ser útil pra cá também. Da uma olhada pfvr

2021-04-20 12:09 UTC, luiz-herique commented on src/routes.ts
> +routers.delete('/api/vote/remove', async (req: Request, resp: Response) => {
Bom dia, avia entendido errado a correção, creio que agora está no modelo correto

2021-04-20 13:54 UTC, MatheusBlanco requested changes

2021-04-20 13:54 UTC, MatheusBlanco commented on src/routes.ts
> +	'/api/complaint/delete',
Retirem essa rota de deletar denúncia

2021-04-20 13:54 UTC, MatheusBlanco commented on src/api/complaint/ComplaintProxy.ts
> +	async deleteComplaint(req: Request, resp: Response): Promise<Response> {
E essa função de deletar denúncia

2021-04-21 01:45 UTC, Victor-Buendia commented
Resolvido os ajustes solicitados!

2021-04-21 14:14 UTC, MatheusBlanco approved these changes

2021-05-08 17:37 UTC, Phe0 reviewed
O caso de erro não está sendo testado no ComplaintProxy

2021-05-08 19:47 UTC, Phe0 approved these changes

2021-05-08 19:47 UTC, merged