Solve #167 Listar denúncias próximas do usuário
Eccoar/2020.2-Eccoar_Gateway pull request #19
Opened 2021-04-30 14:35 UTC by Victor-Buendia

## Conteúdo

Implementação do método que envia parâmetros extras (longitude e latitude) pro filtro de denúncia por geolocalização no repositório do Back.

Neste pull request se realizou:

- US - Filtro de denúncia por localização

## Checklist

- [ x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [ x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ x] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [x ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ x] Escrever o título do pull request no formato correto, conforme as referências abaixo:

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:

- Solve #X IssueName (Caso Padrão)
- WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-05-01 00:47 UTC, MatheusBlanco requested changes

2021-05-01 00:47 UTC, MatheusBlanco commented on src/api/complaint/ComplaintProxy.ts
> +					complaintId: Number(req.query.complaintId),
O saleh tinha pedido para transformarem esses parâmetros em variáveis no outro PR, certo? Façam isso aqui também por favor, só pela legibilidade do código.

2021-05-01 00:47 UTC, MatheusBlanco commented on src/routes.ts
> +
Uma dúvida, está adicionando rota e teste da issue de remoção de votos aqui? Por que?

2021-05-01 00:47 UTC, MatheusBlanco commented on src/api/complaint/ComplaintProxy.ts
> +import { Response, Request, request } from 'express';
Esqueci de comentar isso, esse request não é o mesmo do Request?

2021-05-05 22:15 UTC, Arthur-Matos reviewed
Tem conflitos sendo indicados e revisem as mudanças que o blanco apontou

2021-05-08 20:24 UTC, closed without merging