Solve #93 Formulário de Denúncias
Eccoar/2020.2-Eccoar_Gateway pull request #2
Opened 2021-03-20 04:14 UTC by Arthur-Matos

Neste pull request se realizou:
* US 10
* Interligação entre gateway e serviço de denuncias

2021-03-20 17:59 UTC, Phe0 commented on src/routes.ts
> +    console.log(req.body);
A rota deve retornar um erro 400 caso ocorra um erro na controller

2021-03-20 18:37 UTC, devsalula requested changes

2021-03-20 18:37 UTC, devsalula commented on src/api/complaint/ComplaintProxy.ts
> +            axios.post(this.path + '/complaint', req.body).then(response => {
Mudar o nome da rota para `/complaint/new` ou `/complaint/create`

2021-03-20 18:37 UTC, devsalula commented on src/routes.ts
> +    console.log(req.body);
E também pode retirar em console.log daí pfvr.

2021-03-20 20:43 UTC, MatheusBlanco approved these changes

2021-03-20 21:16 UTC, devsalula requested changes
Tamo perto, tem mais algumas modificações!

2021-03-20 21:16 UTC, devsalula commented on src/api/complaint/ComplaintProxy.ts
> +        const res = await axios.post(this.path + '/complaint/create', req.body);
Show! A Conexão com a api de Complaint tá funcionando 10!
Mas aqui vocês vão precisar de um try-catch para lidar com a situação em que ocorre algum erro lá na api.
Sugiro fazer algo parecido com isso aqui:
```
     async createComplaint(req:Request, resp: Response):
        try{
            const res = await axios.post(this.path + '/complaint/create', req.body);
            resp.sendStatus(res.status);
        } catch(e) {
            resp.status(e.response.status).json(e.response.data);
        }
```

Dessa forma o front fica sabendo quando o foi o tipo de erro que ocorreu na API de Complaint

2021-03-20 21:16 UTC, devsalula commented on src/api/complaint/ComplaintProxy.ts
> +    async createComplaint(req:Request): Promise<Response>{
Tem que importart o tipo Request lá no Express.

2021-03-20 22:18 UTC, devsalula requested changes

2021-03-20 22:18 UTC, devsalula commented on src/routes.ts
> +        await complaintProxy.createComplaint(req);
Falta o resp ser passado como parâmetro. E como a resposta vai ser passada na controller, não precisa desse bloco try-catch na rota.

2021-03-20 22:18 UTC, devsalula commented on src/api/complaint/ComplaintProxy.ts
> +            return resp.status(err.response.status).json(e.response.data);
aonde está `e.response.data`, deve ser `err.response.data`

2021-03-21 00:49 UTC, devsalula commented
@DLBrianPina @Arthur-Matos tem conflitos

2021-03-21 17:13 UTC, devsalula approved these changes
Boa @Arthur-Matos e @DLBrianPina ! Mandaram Bem!

2021-03-21 17:14 UTC, merged