Solve #165 - Autenticação de usuário
Eccoar/2020.2-Eccoar_Gateway pull request #21
Opened 2021-05-01 15:05 UTC by DLBrianPina

Neste pull request se realizou:

- US 02
- Testes

2021-05-01 15:33 UTC, MatheusBlanco requested changes

2021-05-01 15:33 UTC, MatheusBlanco commented on src/api/middlewares/auth.ts
> +		console.log('---' + token + '---');
Tira esse log aqui pfvr

2021-05-01 15:33 UTC, MatheusBlanco commented on src/routes.ts
>  });
A rota de cadastro está faltando aqui, faz o rebase para podermos testar bonitinho

2021-05-01 21:44 UTC, MatheusBlanco requested changes

2021-05-01 21:44 UTC, MatheusBlanco commented on src/api/middlewares/auth.ts
> +		console.log('---' + token + '---');
Gente, perfeito, mas tirem esse log se não for estritamente necessário, para que eu possa aprovar

2021-05-03 21:41 UTC, MatheusBlanco requested changes
Gente, dêem uma olhada no arquivo de complaintProxy, Tem duas declarações de userId lá que ainda estão em Number e isso está quebrando a adição de votos

![image](https://user-images.githubusercontent.com/37380789/116937094-1c247300-ac3f-11eb-9af1-7b38b02060eb.png)

e 

![image](https://user-images.githubusercontent.com/37380789/116937124-28103500-ac3f-11eb-92de-1c6f9611cc89.png)

2021-05-05 23:09 UTC, MatheusBlanco approved these changes

2021-05-07 03:51 UTC, devsalula requested changes
O middleware ficou maneiro! 🚀 
Mas dêem uma olhada nos comentários.
A rota `DELETE api/complaints` ficou sem autorização, por favor corrija.

2021-05-07 03:51 UTC, devsalula commented on src/api/middlewares/auth.ts
> +			return resp.sendStatus(401);
Quando o usuário não é autenticado e tenta acessar uma rota com um token inválido, ou seja ocorre um erro de autorização, o status correto para se retornar é 403 com a mensagem de `User Forbidden`.  https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/403

2021-05-07 03:51 UTC, devsalula commented on src/routes.ts
> +	authValidator.checkJWT,
Por enquanto pode deixar assim. Mas no futuro, eu quero pedir para ter um outro middleware para validar o JWT dessa rota. Ele no caso vai ter que verificar se a pessoa que está fazendo a solicitação para essa rota é administradora do Eccoar

2021-05-07 03:51 UTC, devsalula commented on src/api/middlewares/auth.ts
> +			return resp.sendStatus(401);
E não esquece de escrever o teste para isso aqui também, por favor 😃

2021-05-07 03:51 UTC, devsalula commented on src/routes.ts
> +	'/api/mailer/send',
Essa rota está duplicada, apaguem a que não tem a autorização do JWT.

2021-05-07 11:26 UTC, DLBrianPina commented on src/routes.ts
> +	authValidator.checkJWT,
Vai haver um role de administrador no futuro?

2021-05-07 13:56 UTC, devsalula commented on src/routes.ts
> +	authValidator.checkJWT,
Vai, a intenção é que tenha um perfil de administrador Eccoar. 
Mas por hora, deixa desse jeito mesmo, não precisa modificar. Comentei só por fins de documentação.

2021-05-08 16:17 UTC, DLBrianPina commented on src/routes.ts
> +	authValidator.checkJWT,
Ok, valeu pelo feedback

2021-05-08 20:24 UTC, closed without merging