WIP #124 Envio de e-mails
Eccoar/2020.2-Eccoar_Gateway pull request #7
Opened 2021-04-03 02:53 UTC by Arthur-Matos

Neste pull request se realizou:

- US 26
- Serviço de envio de email

2021-04-05 18:09 UTC, MatheusBlanco requested changes, later dismissed
Parabéns galera! Só lembrem de colocar os testes

2021-04-05 18:11 UTC, MatheusBlanco approved these changes
Boa galera!

2021-04-10 16:05 UTC, MatheusBlanco commented
Gente, ainda está em WIP. Qual a situação deste PR?

2021-04-10 21:17 UTC, MatheusBlanco commented
@Arthur-Matos e @DLBrianPina conflitos aqui

2021-04-11 18:19 UTC, Phe0 approved these changes

2021-04-11 18:20 UTC, merged