Detalhamento da denúncia #125
Eccoar/2020.2-Eccoar_Gateway pull request #8
Opened 2021-04-03 04:36 UTC by luiz-herique

Co-authored-by: Pedro Feo <pheofo@gmail.com>

## Conteúdo

Deve descrever de forma sucinta as principais alterações realizadas no pull request, de preferência em formato de bullet points.

Neste pull request se realizou:

- US 00
- Testes
- Correção de bug ao...

## Checklist

- [ ] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [ ] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ ] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [ ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ ] Escrever o título do pull request no formato correto, conforme as referências abaixo:

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:

- Solve #X IssueName (Caso Padrão)
- WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-04-03 15:35 UTC, devsalula commented
@Victor-Buendia e @luiz-herique , porque vocês fecharam esse PR?

2021-04-05 23:14 UTC, devsalula commented
@Victor-Buendia e @luiz-herique  ainda estou no aguardo da resposta!!!!

2021-04-06 13:44 UTC, Victor-Buendia commented
@devsalula Reabri aqui. Não tinha visto que o Luiz fechou. Não sei por que fechou também.

2021-04-06 13:59 UTC, MatheusBlanco approved these changes

2021-04-06 13:59 UTC, Victor-Buendia commented
@devsalula e @guilhesme23 podem revisar!

2021-04-07 17:51 UTC, devsalula requested changes
Só apaga esse ponto e vírgula duplicado que eu aprovo aqui.

2021-04-07 17:51 UTC, devsalula commented on src/api/complaint/ComplaintProxy.ts
> +            return resp.status(res.status).json(res.data);;
Ponto e vírgula duplicado kkk

2021-04-07 22:15 UTC, devsalula approved these changes
Show Guys, Parabéns

2021-04-07 22:15 UTC, merged